//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bill()
        {
            this.billitems = new HashSet<billitem>();
            this.delivered_expences = new HashSet<delivered_expences>();
        }
    
        public int id { get; set; }
        public int vehicle_number { get; set; }
        public string invoice_number { get; set; }
        public int date { get; set; }
        public decimal total_amount { get; set; }
        public decimal vat { get; set; }
        public Nullable<int> admin_id { get; set; }
        public System.DateTime updated_at { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> sync_id { get; set; }
        public decimal total_Weight { get; set; }
        public decimal total_exp { get; set; }
        public Nullable<int> fiscalyear_id { get; set; }
        public decimal grosstoal { get; set; }
        public decimal nettotal { get; set; }
        public decimal discount { get; set; }
        public decimal paid { get; set; }
        public decimal due { get; set; }
        public Nullable<int> customer_id { get; set; }
    
        public virtual admin admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billitem> billitems { get; set; }
        public virtual customer customer { get; set; }
        public virtual fiscalyear fiscalyear { get; set; }
        public virtual vehicle vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivered_expences> delivered_expences { get; set; }
    }
}
