//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerpyment
    {
        public int id { get; set; }
        public decimal amount { get; set; }
        public Nullable<int> date { get; set; }
        public System.DateTime updated_at { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> sync_id { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
