//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderitemlist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orderitemlist()
        {
            this.tripitems = new HashSet<tripitem>();
            this.tripondelivereditems = new HashSet<tripondelivereditem>();
        }
    
        public int id { get; set; }
        public string sender_name { get; set; }
        public string sender_phone { get; set; }
        public string itemname { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string pice { get; set; }
        public string description { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> date { get; set; }
        public Nullable<int> location_from { get; set; }
        public Nullable<int> location_too { get; set; }
        public Nullable<int> orderitemtype_id { get; set; }
        public Nullable<int> admin_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<int> sync_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string unit { get; set; }
        public string deliveryplace { get; set; }
        public string receivername { get; set; }
        public string receiverphone { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual location location { get; set; }
        public virtual location location1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tripitem> tripitems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tripondelivereditem> tripondelivereditems { get; set; }
        public virtual orderitemtype orderitemtype { get; set; }
    }
}
