//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class partiesledger_payments
    {
        public string title { get; set; }
        public int date { get; set; }
        public decimal amount { get; set; }
        public Nullable<int> parties_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime upadated_at { get; set; }
        public Nullable<int> fiscalyear_id { get; set; }
    
        public virtual fiscalyear fiscalyear { get; set; }
        public virtual party party { get; set; }
    }
}
