//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagementSystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransportManagementEntities : DbContext
    {
        public TransportManagementEntities()
            : base("name=TransportManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<advance> advances { get; set; }
        public virtual DbSet<billitem> billitems { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<customerpaid> customerpaids { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<delivered_expences> delivered_expences { get; set; }
        public virtual DbSet<expence> expences { get; set; }
        public virtual DbSet<expencescategory> expencescategories { get; set; }
        public virtual DbSet<finance> finances { get; set; }
        public virtual DbSet<fiscalyear> fiscalyears { get; set; }
        public virtual DbSet<incomecategory> incomecategories { get; set; }
        public virtual DbSet<income> incomes { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<orderitemlist> orderitemlists { get; set; }
        public virtual DbSet<orderitemtype> orderitemtypes { get; set; }
        public virtual DbSet<otherexpitem> otherexpitems { get; set; }
        public virtual DbSet<otherexp> otherexps { get; set; }
        public virtual DbSet<paidadvance> paidadvances { get; set; }
        public virtual DbSet<paidfinance> paidfinances { get; set; }
        public virtual DbSet<paidsalary> paidsalarys { get; set; }
        public virtual DbSet<salary> salaries { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<systemsetting> systemsettings { get; set; }
        public virtual DbSet<taxcategory> taxcategories { get; set; }
        public virtual DbSet<tax> taxes { get; set; }
        public virtual DbSet<taxpaid> taxpaids { get; set; }
        public virtual DbSet<tripitem> tripitems { get; set; }
        public virtual DbSet<tripondelivered> tripondelivereds { get; set; }
        public virtual DbSet<tripondelivereditem> tripondelivereditems { get; set; }
        public virtual DbSet<trip> trips { get; set; }
        public virtual DbSet<vehicle> vehicles { get; set; }
    }
}
