//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tripitem
    {
        public int id { get; set; }
        public Nullable<int> item_id { get; set; }
        public string sender_name { get; set; }
        public string sender_phone { get; set; }
        public string sender_addrress { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<int> date { get; set; }
        public Nullable<int> location_form { get; set; }
        public Nullable<int> location_too { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> bill_id { get; set; }
        public Nullable<int> admin_id { get; set; }
        public Nullable<int> orderitemtype_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<int> sync_id { get; set; }
        public string deliver_place { get; set; }
        public Nullable<bool> active { get; set; }
        public string receivername { get; set; }
        public string receiverphone { get; set; }
        public Nullable<int> fiscalyear_id { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual fiscalyear fiscalyear { get; set; }
        public virtual location location { get; set; }
        public virtual location location1 { get; set; }
        public virtual orderitemlist orderitemlist { get; set; }
        public virtual orderitemtype orderitemtype { get; set; }
        public virtual trip trip { get; set; }
    }
}
